### ISSUE TITLE
SteamVR Support

### ISSUE THREAD

**Issue by velocity7** [gusmanb/PSVRFramework#10]
Hey, excellent job on the project so far. I was just curious if you plan on doing anything like connecting this up to SteamVR, in a manner similar to the way VRidge does it with phones?

Also, any idea on what camera may eventually be needed for positional tracking? I do have a PlayStation Eye (PS3) still on me that I might be able to hook up, but it can only manage 240p120 or 480p60. In comparison, the PlayStation 4 Camera can manage 800p60 or 400p120 (16:10).

Looking forward to future updates with this project!

**Comment by MaVe-64** [comment]
I think the position tracking part is looked into by hipstersloth. 
https://groups.google.com/forum/m/#!forum/psmoveservice

**Comment by mungewell** [comment]
Nice link!!

I was about to say that perhaps full position tracking is beyond this project, however the approach of UDP streaming data PSMoveService seems 'workable'.

Just for sake of mixing it up we should use the Kinect ;-)

**Comment by Sebihunter** [comment]
I have been doing a lot of research on existing programs already: https://www.reddit.com/r/Vive/comments/5assli/how_i_kinda_got_psvr_running_with_steamvr_vive/

So basicly what we need is a OpenVR driver (https://github.com/ValveSoftware/openvr/tree/master/samples/driver_sample) in which we can inject FreeTrack/OpenTrack data from both PSMoveService (position) and PSVRFramework (rotation) - My tutorial pretty much works already using a Move controller for both data BUT using the inbuilt SteamVR mirror is a no-go sadly (capped to 28 FPS)

**Comment by ozzeruk** [comment]
There must be code somewhere for an OpenVR driver that renders to a monitor/HDMI at a sufficiently high rate - like you say the SteamVR mirror running at 90FPS would be perfect. The second link Sebihunter provides would be a good start for someone creating one, but I'm sure it's been done before.

PSMoveService with multiple cameras works very nicely for tracking PS Move controllers, I have 3 tracked by 4 cameras and while it isn't yet perfect, it's not a million miles off what you see in PSVR (i.e. a bit of shaking etc). Hipstersloth over on that project is working on getting the headset tracked. That project is definitely the thing to use for tracking.

**Comment by mungewell** [comment]
I don't mean to sound negative, but I think that position tracking is a little beyond _this_ project, but I am certainly open to sharing information and encouraging hacking/reverse engineering.

IFAIK PSVRFramework does not yet track (at least export) rotation. There is some work on doing sensor fusion,  but for a properly tracked solution you **need** the camera information. Any fusion done for the VR player would be rotation only.

I am really excited that PSMoveService might soon support PSVR with SteamVR. The would fulfill my personal goal of playing Project Cars on the PSVR. I'd be a little scared of putting too many software layers in the stack though...

For the end goal, we perhaps evaluate how much/far we want to do/go with each project.

**Comment by gusmanb** [comment]
@velocity7 That is beyond the scope of the toolbox and framework, the framework target is to control completely the PS VR set and the toolbox will be a source for controlling the set settings and receive all the possible info about it, I'm struggling with the sensor data because I want to provide other apps with neat filtered info, but in a begining with just the raw data from the sensors that target has been achieved.

When I manage to filter correctly the data then the next goal is to broadcast this in a compatible way with opentrack (not sure if PSMoveService allows to send data, maybe an integration among both softwares could be factible).

Also I want to add a listener for remote calls to the PS VR settings, that would allow other programs like VR players to change the config when they need to enter/leave the VR mode.
