### ISSUE TITLE
Download flagged as Malicious

### ISSUE THREAD

**Issue by mungewell** [gusmanb/PSVRFramework#2]
Maybe Chrome is over protective...
![malicious](https://cloud.githubusercontent.com/assets/236907/19839073/768f14e0-9ea1-11e6-9db2-dd173ec8e3aa.png)

**Comment by gusmanb** [comment]
If you have vs 2015 installed just clone the repo and compile it, safer.

Does chrome tell you what type of threat it presents? I suppose its because
contains the libusb wrapper library, but is strange.

**Comment by mungewell** [comment]
Do you have the MD5Sum of what you uploaded? I can check whether I'm downloading the same, and that would make me confident to run it...

Don't have Win32/64 dev enviroment set up, I work mainly in Linux.

**Comment by gusmanb** [comment]
Ok, checked it myself and the problem was the file server I used, Google has it flagged as malicious.

So, instead of using an external file hosting for binaries I created a Release here on github with all the files and everything now downloads ok from Chrome.

-A side question, if you are working on linux, can you check if the tool works on it? I have used a libusub wrapper which claims to be 100% portable and work on linux and windows with no changes, as the interface is really simple the WinForms Mono implementation must also work, so in theory it should run out-of-the-box just by having Mono 4.4 or higher installed.

Cheers.
