### ISSUE TITLE
Issue with display in VR mode

### ISSUE THREAD

**Issue by sithhunter09** [gusmanb/PSVRFramework#54]
Cinematic mode works perfectly for me. However, when I use the VR mode, while I do get a display, it seems like it's either split or wrapping around on itself (i cant honestly tell), and is incredibly disorienting and quite literally painful to look at. What may be going wrong here?

**Comment by mungewell** [comment]
In VR mode, the PC needs to render the two views (side by side) to create the illusion of a 3D image. Normally your game, or VR plugin would do this for you. 
For example (a test image):
https://cloud.githubusercontent.com/assets/236907/20165308/46ae57ba-a6c9-11e6-8d2b-06d152353266.png

See #27 for more details.

When viewed on the HDMI pass through, the PSVR will pick one of these and de-distort it so that the TV image looks OK.
